import {jsPDF} from 'jspdf';
import * as pdfjs from 'pdfjs-dist/build/pdf.mjs';
import {sheet,testAnswers} from './sheet.js';
import readExcelFile from 'read-excel-file/browser';
import {parseCsv,importStudents} from './roster.js';
import {W,H,bubble,detectMarkers} from './engine.js';
import {readSheet} from './reader.js';
import {setupCamera} from './camera.js';
pdfjs.GlobalWorkerOptions.workerSrc='./vendor/pdf.worker.min.mjs';
const $=id=>document.getElementById(id);let busy=false,previewTicket=0,students=[],selected=0,fileSheets=[];
const marksById=new Map();
const status=message=>$('status').textContent=message;
const currentStudent=()=>students[selected]||null;
function marks(student=currentStudent()){const id=student?.id||'single';if(!marksById.has(id))marksById.set(id,Array(60).fill(''));return marksById.get(id);}
function form(){return {organization:$('organization').value.trim(),subtitle:$('subtitle').value.trim(),count:Math.max(1,Math.min(60,Math.trunc(Number($('count').value)||20))),student:currentStudent()};}
async function preview(){const ticket=++previewTicket;const c=await sheet(form(),[...marks()]);if(ticket!==previewTicket)return;const p=$('preview');p.width=W;p.height=H;p.getContext('2d').drawImage(c,0,0);}
function editor(){const host=$('answerEditor');host.replaceChildren();for(let q=0;q<form().count;q++){const label=document.createElement('label');label.textContent=`Questão ${q+1}`;const select=document.createElement('select');for(const value of ['','A','B','C','D'])select.add(new Option(value||'Em branco',value));select.value=marks()[q];select.onchange=()=>{marks()[q]=select.value;preview().catch(e=>status(e.message));};label.append(select);host.append(label);}}
for(const id of ['organization','subtitle','count'])$(id).addEventListener('input',()=>{if(id==='count')editor();preview().catch(e=>status(e.message));});
$('count').addEventListener('change',()=>{$('count').value=form().count;});
$('studentSelect').onchange=()=>{selected=Number($('studentSelect').value);editor();preview().catch(e=>status(e.message));};
$('fillSequence').onclick=()=>{const answers=marks();testAnswers(form().count).forEach((a,i)=>answers[i]=a);editor();preview().catch(e=>status(e.message));};
$('clearMarks').onclick=()=>{marks().fill('');editor();preview().catch(e=>status(e.message));};
$('preview').onclick=event=>{if(busy)return;const canvas=$('preview'),r=canvas.getBoundingClientRect(),x=(event.clientX-r.left)*W/r.width,y=(event.clientY-r.top)*H/r.height;for(let q=0;q<form().count;q++)for(let a=0;a<4;a++){const [bx,by]=bubble(q,a);if(Math.hypot(x-bx,y-by)<22){marks()[q]=marks()[q]==='ABCD'[a]?'':'ABCD'[a];editor();preview().catch(e=>status(e.message));return;}}};
async function guard(fn){if(busy)return;busy=true;const controls=[...document.querySelectorAll('#generator input,#generator select,#generator button,#uploads,#openCamera,#nativeCamera,#cameraFile')];controls.forEach(el=>el.disabled=true);try{await fn();}catch(e){status(e.message||String(e));}finally{busy=false;controls.forEach(el=>el.disabled=false);$('generateAll').disabled=!students.length;}}
async function makePdf(all){const options=form(),list=all?students:[options.student];if(!list.length)throw Error('Importe os alunos primeiro.');const pdf=new jsPDF({unit:'mm',format:'a4'});for(let i=0;i<list.length;i++){status(`Gerando folha ${i+1} de ${list.length}…`);const c=await sheet({...options,student:list[i]},[...marks(list[i])]);if(i)pdf.addPage();pdf.addImage(c.toDataURL('image/png'),'PNG',0,0,210,297,undefined,'FAST');c.width=1;c.height=1;await new Promise(r=>setTimeout(r,0));}pdf.save(all?'folhas-resposta-alunos.pdf':'folha-resposta.pdf');status(`${list.length} folha(s) gerada(s). As marcações de teste foram incluídas apenas onde você preencheu.`);}
$('generate').onclick=()=>guard(()=>makePdf(false));$('generateAll').onclick=()=>guard(()=>makePdf(true));
function displayRoster(){const select=$('studentSelect');select.replaceChildren();students.forEach((s,i)=>select.add(new Option(`${s.name} · ${s.grade} / ${s.classroom}`,String(i))));select.value='0';const body=$('rosterTable');body.replaceChildren();for(const s of students){const row=document.createElement('tr');for(const value of [s.school,s.grade,s.classroom,s.name]){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}body.append(row);}$('rosterDetails').hidden=false;$('generateAll').textContent=`Gerar PDF dos ${students.length} alunos ↓`;$('importStatus').textContent=`${students.length} aluno(s) importado(s). Folhas inicialmente em branco.`;editor();preview().catch(e=>status(e.message));}
async function useSheet(index){try{const imported=await importStudents(fileSheets[index].data);students=imported;selected=0;marksById.clear();$('importErrors').hidden=true;displayRoster();status('Alunos importados. Gere as folhas ou preencha uma delas para teste.');}catch(e){$('importErrors').hidden=false;$('importErrors').textContent=e.message+ (students.length?'\nOs alunos anteriores foram mantidos.':'');status('Revise a planilha: a importação não foi concluída.');}}
$('rosterFile').onchange=()=>guard(async()=>{const file=$('rosterFile').files[0];if(!file)return;$('importErrors').hidden=true;status('Lendo a planilha…');try{if(file.size>10e6)throw Error('Use uma planilha de até 10 MB.');const extension=file.name.split('.').pop().toLowerCase();if(extension==='csv'){const bytes=await file.arrayBuffer();let text=new TextDecoder('utf-8').decode(bytes);if(text.includes('\uFFFD'))text=new TextDecoder('windows-1252').decode(bytes);fileSheets=[{sheet:file.name,data:parseCsv(text)}];}else if(extension==='xlsx'){fileSheets=await readExcelFile(file);}else throw Error('Use Excel .xlsx ou CSV. Para .xls, salve uma cópia em .xlsx.');if(!fileSheets.length)throw Error('Nenhuma aba encontrada.');const select=$('sheetChoice');select.replaceChildren();fileSheets.forEach((s,i)=>select.add(new Option(s.sheet,String(i))));$('sheetChoiceLabel').hidden=fileSheets.length<2;await useSheet(0);}catch(e){$('importErrors').hidden=false;$('importErrors').textContent=e.message;status('Não foi possível importar a planilha.');}finally{$('rosterFile').value='';}});
$('sheetChoice').onchange=()=>guard(()=>useSheet(Number($('sheetChoice').value)));
$('csvTemplate').onclick=()=>{const url=URL.createObjectURL(new Blob(['\ufeffESCOLA;SÉRIE;TURMA;NOME\r\n'],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='modelo-alunos.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);};
async function* pages(file){if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')){const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false}).promise;try{for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),base=p.getViewport({scale:1}),v=p.getViewport({scale:Math.min(1800/base.width,2500/base.height)}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;yield {c,label:`${file.name} · página ${i}`};p.cleanup();}}finally{await pdf.destroy();}}else{const img=await createImageBitmap(file),scale=Math.min(1,1800/img.width,2500/img.height),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);img.close();yield {c,label:file.name};}}
function manual(c){return new Promise(resolve=>{$('alignment').hidden=false;const cv=$('alignCanvas');cv.width=c.width;cv.height=c.height;const ctx=cv.getContext('2d'),points=[],labels=['superior esquerdo','superior direito','inferior direito','inferior esquerdo'];const draw=()=>{ctx.drawImage(c,0,0);ctx.fillStyle='#e74722';points.forEach(([x,y],i)=>{ctx.beginPath();ctx.arc(x,y,12,0,7);ctx.fill();ctx.font='30px Arial';ctx.fillText(i+1,x+15,y);});$('alignPrompt').textContent=`Clique no centro do quadrado ${labels[points.length]} da folha (considerando a orientação do texto).`;};const done=p=>{cv.onclick=null;$('alignment').hidden=true;resolve(p);};cv.onclick=e=>{const r=cv.getBoundingClientRect();points.push([(e.clientX-r.left)*cv.width/r.width,(e.clientY-r.top)*cv.height/r.height]);if(points.length===4)done(points);else draw();};$('cancelAlign').onclick=()=>done(null);draw();$('alignment').scrollIntoView({behavior:'smooth',block:'start'});});}
function addError(message){const p=document.createElement('p');p.className='error';p.textContent=message;$('errors').append(p);}
function responseLabel(result,q){const a=result.answers[q];if(a==='BRANCO')return 'Em branco';if(a==='REVISAR')return 'Duvidosa';if(a==='MULTIPLA')return result.densities[q].map((v,i)=>v>=.5?'ABCD'[i]:null).filter(Boolean).join(' + ')+' (múltipla)';return a;}
function renderReading(result,label){
 const {out,answers,densities}=result,c=document.createElement('canvas');c.width=W;c.height=H;const ctx=c.getContext('2d');ctx.putImageData(new ImageData(out.data,W,H),0,0);
 for(let q=0;q<answers.length;q++)for(let a=0;a<4;a++)if(densities[q][a]>.12){const[x,y]=bubble(q,a);ctx.beginPath();ctx.arc(x,y,17,0,7);ctx.strokeStyle=answers[q]==='REVISAR'||answers[q]==='MULTIPLA'?'#d17a00':'#087d73';ctx.lineWidth=3;ctx.stroke();}
 const card=document.createElement('article');card.className='result';const heading=document.createElement('h3');const student=students.find(s=>s.id===result.studentId);heading.textContent=student?student.name:label;card.append(heading);if(student){const identification=document.createElement('p');identification.className='hint';identification.textContent=`${student.school} · Série ${student.grade} · Turma ${student.classroom}`;card.append(identification);}else if(result.studentId){const note=document.createElement('p');note.className='hint';note.textContent='Folha identificada. Importe a mesma planilha neste dispositivo antes de ler para exibir o nome do aluno.';card.append(note);}
 const meta=document.createElement('p');meta.className='hint';const uncertain=answers.filter(x=>['REVISAR','MULTIPLA'].includes(x)).length;meta.textContent=`${answers.length} questões lidas${uncertain?` · ${uncertain} marcação(ões) duvidosa(s) ou múltipla(s)`:''}. Confira com a folha fotografada.`;card.append(meta);
 const layout=document.createElement('div');layout.className='reading-layout';const grid=document.createElement('div');grid.className='reading-grid';
 for(let start=0;start<answers.length;start+=20){const table=document.createElement('table');table.className='reading-table';const thead=document.createElement('thead'),hr=document.createElement('tr');for(const text of ['Questão','Resposta']){const th=document.createElement('th');th.scope='col';th.textContent=text;hr.append(th);}thead.append(hr);table.append(thead);const body=document.createElement('tbody');for(let q=start;q<Math.min(start+20,answers.length);q++){const tr=document.createElement('tr');if(['REVISAR','MULTIPLA'].includes(answers[q]))tr.className='uncertain';const num=document.createElement('td'),value=document.createElement('td');num.textContent=q+1;value.textContent=responseLabel(result,q);tr.append(num,value);body.append(tr);}table.append(body);grid.append(table);}
 layout.append(grid);const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Ver imagem lida';const img=new Image();img.alt='Folha alinhada com as marcações detectadas';img.src=c.toDataURL('image/jpeg',.7);details.append(summary,img);layout.append(details);card.append(layout);$('results').append(card);
}
function processFiles(files){return guard(async()=>{
 if(!files.length)return;$('errors').replaceChildren();$('results').replaceChildren();$('results').className='';$('resultCount').textContent='';$('progress').hidden=false;$('progress').max=files.length;let readings=0,failures=0,skipped=0;
 try{for(let f=0;f<files.length;f++){const file=files[f];try{if(file.size>40e6)throw Error('Use arquivos de até 40 MB.');for await(const {c,label}of pages(file)){status(`Lendo ${label}…`);await new Promise(r=>setTimeout(r,15));try{const pixels=c.getContext('2d').getImageData(0,0,c.width,c.height);let points=detectMarkers(pixels),result;
 if(points){try{result=readSheet(pixels,points);}catch(e){if(e.message.includes('cartões antigos')||e.message.includes('Formato da folha'))throw e;}}
 if(!result){status('Ajuste os quatro cantos desta página para continuar.');points=await manual(c);if(!points){skipped++;continue;}result=readSheet(pixels,points);}
 renderReading(result,label);readings++;$('resultCount').textContent=`· ${readings} folha(s)`;
 }catch(e){failures++;addError(`${label}: ${e.message}`);}}}catch(e){failures++;addError(`${file.name}: ${e.message}`);}$('progress').value=f+1;}
 status(`${readings} folha(s) lida(s)${failures?` · ${failures} falha(s)`:''}${skipped?` · ${skipped} página(s) pulada(s)`:''}.`);
 if(!readings){$('results').className='results-empty';$('results').textContent='Nenhuma leitura disponível. Confira as mensagens acima e tente uma nova foto.';}
 else $('results').scrollIntoView({behavior:'smooth',block:'start'});
 }finally{$('progress').hidden=true;$('uploads').value='';}
});}
$('uploads').onchange=()=>processFiles([...$('uploads').files]);
setupCamera({validate:()=>{},onFiles:processFiles,status,isBusy:()=>busy});
// The site exposes only the current generator settings; there are no records to save.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_test_sheet',description:'Configura o cabeçalho e a quantidade de questões da folha exibida, sem baixar ou salvar arquivos.',inputSchema:{type:'object',properties:{organization:{type:'string'},subtitle:{type:'string'},count:{type:'integer',minimum:1,maximum:60}},required:['count'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){if(busy)throw Error('Aguarde a leitura atual.');if(!input||!Number.isInteger(input.count)||input.count<1||input.count>60||['organization','subtitle'].some(k=>input[k]!==undefined&&(typeof input[k]!=='string'||input[k].length>100)))throw Error('Dados inválidos.');$('organization').value=input.organization||'';$('subtitle').value=input.subtitle||'';$('count').value=input.count;editor();await preview();return {questions:input.count,choices:'ABCD'};}})).catch(()=>{});}catch{}}
editor();preview().catch(e=>status(e.message));
