import {downloadSchoolWorkbook} from './export-school.js';
import {watchSession,identity,listSchools,loginSchool,loginMaster,logout,createSchool,loadRoster,listScans,listAllScans,explainFirebase} from './firebase-client.js';
export function mountAccess({onSchool,isBusy}){
 const $=id=>document.getElementById(id);let schools=[],active=null,master=false,epoch=0,working=false;
 const message=text=>$('accessStatus').textContent=text;
 const text=(tag,value)=>{const el=document.createElement(tag);el.textContent=value;return el;};
 function lock(value){working=value;document.querySelectorAll('#accessPanel button,#accessPanel input,#accessPanel select,#adminPanel button,#adminPanel input,#adminPanel select').forEach(el=>el.disabled=value);}
 async function action(fn){if(working||isBusy())return;lock(true);message('Aguarde…');try{await fn();}catch(e){message(explainFirebase(e));}finally{lock(false);}}
 async function refreshSchools(){schools=await listSchools();for(const id of ['loginSchool','adminSchoolSelect']){const select=$(id);select.replaceChildren(new Option('Selecione a escola',''));for(const s of schools)select.add(new Option(s.name,s.id));}const host=$('adminSchools');host.replaceChildren();for(const s of schools){const row=text('li',s.name);host.append(row);}if(!schools.length)message('Nenhuma escola cadastrada. O administrador deve cadastrar a primeira escola.');}
 async function refreshHistory(){const school=active,ticket=epoch;if(!school)return;const host=$('scanHistory');host.textContent='Carregando leituras salvas…';try{const scans=await listScans(school.id);if(ticket!==epoch||active?.id!==school.id)return;host.replaceChildren();if(!scans.length){host.textContent='Nenhuma leitura salva nesta escola.';return;}for(const s of scans){const details=document.createElement('details');const date=s.createdAt?.toDate?.().toLocaleString('pt-BR')||'';details.append(text('summary',`${s.name} · ${s.discipline||'Sem disciplina identificada'} · ${date}`));details.append(text('p',`Série ${s.grade||'—'} · Turma ${s.classroom||'—'}`));details.append(text('p',(s.answers||[]).map((a,i)=>`${i+1}: ${a}`).join(' · ')));host.append(details);}}catch(e){if(ticket===epoch)host.textContent=explainFirebase(e);}}
 async function openSchool(school){const ticket=epoch,data=await loadRoster(school.id);if(ticket!==epoch)return;epoch++;active=school;await onSchool(school,data);$('schoolWorkspace').hidden=false;$('adminPanel').hidden=true;$('accessPanel').hidden=true;$('sessionBar').hidden=false;$('sessionSchool').textContent=school.name;$('backAdmin').hidden=!master;message('');await refreshHistory();}
 watchSession(async user=>{const ticket=++epoch;active=null;master=false;$('exportStatus').textContent='';$('schoolWorkspace').hidden=true;$('adminPanel').hidden=true;$('sessionBar').hidden=true;await onSchool(null,{students:[],revision:0});$('accessPanel').hidden=!!user;if(!user){message('Escolha sua escola e informe a senha.');return;}try{const who=await identity(user);if(ticket!==epoch)return;master=who.master;if(master){$('adminPanel').hidden=false;$('sessionBar').hidden=false;$('sessionSchool').textContent='Administração';$('backAdmin').hidden=true;message('Cadastre uma escola e defina a senha de acesso.');await refreshSchools().catch(e=>message(explainFirebase(e)));}else {await refreshSchools();if(ticket!==epoch)return;await openSchool(who.school);}}catch(e){if(ticket!==epoch)return;await logout();message(explainFirebase(e));}});
 $('schoolLoginForm').onsubmit=e=>{e.preventDefault();action(async()=>{if(!$('loginSchool').value)throw Error('Selecione sua escola.');await loginSchool($('loginSchool').value,$('schoolPassword').value);$('schoolPassword').value='';});};
 $('masterLoginForm').onsubmit=e=>{e.preventDefault();action(async()=>{await loginMaster($('masterPassword').value);$('masterPassword').value='';});};
 $('newSchoolForm').onsubmit=e=>{e.preventDefault();action(async()=>{await createSchool($('newSchoolName').value,$('newSchoolPassword').value);$('newSchoolName').value='';$('newSchoolPassword').value='';await refreshSchools();message('Escola cadastrada. Ela já aparece na lista de acesso.');});};
 $('adminOpenSchool').onclick=()=>action(async()=>{const school=schools.find(s=>s.id===$('adminSchoolSelect').value);if(!school)throw Error('Selecione a escola.');await openSchool(school);});
 $('reloadSchools').onclick=()=>action(refreshSchools);
 $('logout').onclick=()=>{if(isBusy()||working)return;logout().catch(e=>message(explainFirebase(e)));};
 $('backAdmin').onclick=async()=>{if(isBusy()||working)return;epoch++;active=null;await onSchool(null,{students:[],revision:0});$('schoolWorkspace').hidden=true;$('adminPanel').hidden=false;$('sessionSchool').textContent='Administração';$('backAdmin').hidden=true;};
 $('exportSchool').onclick=()=>action(async()=>{if(!active)throw Error('Entre em uma escola para exportar.');const school={...active};const button=$('exportSchool');button.disabled=true;$('exportStatus').textContent='Preparando todos os cadastros e leituras…';try{const [roster,scans]=await Promise.all([loadRoster(school.id),listAllScans(school.id)]);await downloadSchoolWorkbook(school,roster.students||[],scans);$('exportStatus').textContent=`Planilha preparada: ${(roster.students||[]).length} aluno(s) e ${scans.length} leitura(s).`;message('Download da planilha Excel iniciado.');}catch(e){$('exportStatus').textContent='Não foi possível exportar: '+explainFirebase(e);throw e;}finally{button.disabled=false;}});
 $('refreshHistory').onclick=()=>refreshHistory();
 refreshSchools().catch(e=>message(explainFirebase(e)));
 return {refreshHistory};
}
